# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Repo2page < Formula
  desc "Convert repositories into single, portable structure-preserving documents."
  homepage "https://github.com/imsncht/repo2page"
  version "1.0.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/imsncht/repo2page/releases/download/v1.0.6/repo2page_1.0.6_darwin_amd64.tar.gz"
      sha256 "7d18d29583b09c9b78fb48f13ad4a4cfae37c9ee6ef174641b9806fc0d550300"

      def install
        bin.install "repo2page"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/imsncht/repo2page/releases/download/v1.0.6/repo2page_1.0.6_darwin_arm64.tar.gz"
      sha256 "9226afff756312220d786a7e8ecb337281bd160fe2f264405029377da086cd03"

      def install
        bin.install "repo2page"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/imsncht/repo2page/releases/download/v1.0.6/repo2page_1.0.6_linux_amd64.tar.gz"
      sha256 "3768138b5b04bb996ae454706dbe4a187040fd3d1d8129cc156f399d645d4462"
      def install
        bin.install "repo2page"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/imsncht/repo2page/releases/download/v1.0.6/repo2page_1.0.6_linux_arm64.tar.gz"
      sha256 "1b5f51af37b3c625e3517eadde1f1355c219d1464a87e1f538660e03d84cb6ab"
      def install
        bin.install "repo2page"
      end
    end
  end

  test do
    system "#{bin}/repo2page --version"
  end
end
