# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Repo2page < Formula
  desc "Convert repositories into single, portable structure-preserving documents."
  homepage "https://github.com/imsncht/repo2page"
  version "1.0.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/imsncht/repo2page/releases/download/v1.0.7/repo2page_1.0.7_darwin_amd64.tar.gz"
      sha256 "2409c3d9e9df21e4362381ad6e796a9d0eb68c2765c4303c8aa021e3c150fd48"

      def install
        bin.install "repo2page"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/imsncht/repo2page/releases/download/v1.0.7/repo2page_1.0.7_darwin_arm64.tar.gz"
      sha256 "c9d782f1a07540636cd54ad09bf4a23f86f0b4670ea7b59451192d5aae3c5d33"

      def install
        bin.install "repo2page"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/imsncht/repo2page/releases/download/v1.0.7/repo2page_1.0.7_linux_amd64.tar.gz"
      sha256 "f83b3762243e5036401dcace7e83b3ad8b404f881f2e72eff7727e4ab33a5362"
      def install
        bin.install "repo2page"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/imsncht/repo2page/releases/download/v1.0.7/repo2page_1.0.7_linux_arm64.tar.gz"
      sha256 "794d9ca00031a90b068f0066661972446da53fd3d4028a07e1ff1bf38da4f962"
      def install
        bin.install "repo2page"
      end
    end
  end

  test do
    system "#{bin}/repo2page --version"
  end
end
