# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Repo2page < Formula
  desc "Convert repositories into single, portable structure-preserving documents."
  homepage "https://github.com/imsncht/repo2page"
  version "1.0.1"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/imsncht/repo2page/releases/download/v1.0.1/repo2page_1.0.1_darwin_amd64.tar.gz"
      sha256 "9ac9619965baf6a229c8563bdf74224f8cb2b19546aedd6ad80e4e6dfef776dd"

      def install
        bin.install "repo2page"
      end
    end
    on_arm do
      url "https://github.com/imsncht/repo2page/releases/download/v1.0.1/repo2page_1.0.1_darwin_arm64.tar.gz"
      sha256 "534244d98c9023015fd7adb8ad7f80803fe63300e6babdc590c0100227162b66"

      def install
        bin.install "repo2page"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/imsncht/repo2page/releases/download/v1.0.1/repo2page_1.0.1_linux_amd64.tar.gz"
        sha256 "8d83b60cf7e6fedf5dfc48e55943514350759660eec49c37f51499c06456b97c"

        def install
          bin.install "repo2page"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/imsncht/repo2page/releases/download/v1.0.1/repo2page_1.0.1_linux_arm64.tar.gz"
        sha256 "b30bfea84e607aedb6249484110095ed59bf7fc732dedfc9757472c34ac0e181"

        def install
          bin.install "repo2page"
        end
      end
    end
  end

  test do
    system "#{bin}/repo2page --version"
  end
end
